# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1024
    min-spare-threads: 30
    accept-count: 5000
  port: 8080
  connection-timeout: 1000ms
  servlet:
    context-path: /

spring:
  application:
    name: paltform-api
  main:
    allow-bean-definition-overriding: true
  # 环境 dev|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      #格式化输出
      #indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
      #设置空如何序列化
    #defaultPropertyInclusion: NON_EMPTY
    deserialization:
        #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    #parser:
        #允许出现特殊字符和转义符
      #allow_unquoted_control_chars: true
        #允许出现单引号
      #allow_single_quotes: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  resources:
    add-mappings: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.platform.entity
  check-config-location: true
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: AUTO
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 0
      #逻辑未删除值
      logic-not-delete-value: 1

#小程序ID
wx:
  appId: wx5d2fa7eda047e3b4
  #小程序密钥
  secret: 37705907b2a1d307ce08966d475d5661
  #商户号
  mchId: 333
  #支付签名
  paySignKey: 444
  #交易类型
  tradeType: JSAPI
  #证书名称，对应不同的商户号
  certName: /cert/apiclient_cert.p12
  #支付回调地址
  notifyUrl: http://wengl.51vip.biz:41224/platform-framework/api/pay/notify
  #获取code的请求地址
  code: https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=%s&state=STAT#wechat_redirect
  #获取Web_access_tokenhttps的请求地址
  webAccessTokenhttps: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code
  #拉取用户信息的请求地址
  userMessage: https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s&lang=zh_CN
  #微信统一下单接口路径
  uniformorder: https://api.mch.weixin.qq.com/pay/unifiedorder
  #退款地址
  refundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款查询地址
  refundqueryUrl: https://api.mch.weixin.qq.com/pay/refundquery
  #微信查询订单状态
  orderquery: https://api.mch.weixin.qq.com/pay/orderquery
  #微信请求access_token接口
  accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
  #获取小程序码
  wXACodeUnlimit: https://api.weixin.qq.com/wxa/getwxacodeunlimit
  #安全起见，暴露的短信接口需要配置有效的请求IP
  #企业付款
  orgPay: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
  sms:
    validIp: 127.0.0.1



logging:
  config: classpath:logback-spring.xml
