spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    代码生成通过读取driverClassName来判断数据库类型
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/final?allowMultiQueries=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
#    driverClassName: oracle.jdbc.driver.OracleDriver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 0
    host: 39.106.224.224
    port: 6379
    password: aiyike   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 10  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
      shutdown-timeout: 100
  cache:
    type: redis
  data:
    elasticsearch:
      # elasticsearch.yml 文件中的 cluster.name
      cluster-name: docker-cluster
      # elasticsearch 调用地址，多个使用“,”隔开
      cluster-nodes: ${ES_HOST:39.106.224.224}:${ES_PORT:9300}
      repositories:
        enabled: true


